version: 2.1
workflows:
  env-vars:
    jobs:
      - build:
          context: udagram
jobs:
  build:
    working_directory: /udagram-api-user
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip=9.0.0-r1
            pip install \
              docker-compose==1.15.0 \
              awscli==1.11.76
      - run:
          name: docker build
          command: |
            docker build -t udagram-api-user .
      - deploy:
          name: Push application Docker image
          command: |
            docker login -u $DOCKER_HUB_USER_ID -p $DOCKER_HUB_PWD
            docker tag udagram-api-user $DOCKER_HUB_USER_ID/udagram-api-user:latest
            docker tag udagram-api-user $DOCKER_HUB_USER_ID/udagram-api-user:v2
            docker push $DOCKER_HUB_USER_ID/udagram-api-user:latest
            docker push $DOCKER_HUB_USER_ID/udagram-api-user:v2
