apiVersion: v1
kind: Service
metadata:
  name: udagram-api-user
  labels:
    service: udagram-api-user
spec:
  ports:
  - port: 8080
    name: "8080"
    targetPort: 8080
  selector:
    service: udagram-api-user
