apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-api-user
  labels:
    app: udagram-api-user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-api-user
  template:
    metadata:
      labels:
        app: udagram-api-user
    spec:
      containers:
      - name: udagram-api-user
        image: okmarq/udagram-api-user:v2
        imagePullPolicy: Always
        ports:
          - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        envFrom:
          - configMapRef:
              name: env-config
          - secretRef:
              name: env-secret