version: 2.1
workflows:
  env-vars:
    jobs:
      - build:
          context: udagram
jobs:
  build:
    working_directory: /udagram-compose
    docker:
      - image: docker:17.05.0-ce-git
        auth:
          username: $DOCKER_HUB_USER_ID
          password: $DOCKER_HUB_PWD
        environment:
          POSTGRES_USERNAME: postgres
          POSTGRES_PASSWORD: 2kuljones
          POSTGRES_HOST: udagram-database.c6l2kjupeisc.us-east-2.rds.amazonaws.com
          POSTGRES_DB: udagram
          AWS_BUCKET: arn:aws:s3:::udagram-115477439975
          AWS_REGION: us-east-2
          AWS_PROFILE: admin
          JWT_SECRET: testing
          URL: http://localhost:8100
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip=9.0.0-r1
            pip install \
              docker-compose==1.15.0 \
              awscli==1.11.76 \
              --upgrade pip \
              --upgrade docker-compose \
              --upgrade awscli
      - run:
          name: docker
          command: |
            docker --version
      - run:
          name: docker-compose
          command: |
            docker-compose --version
      - run:
          name: aws
          command: |
            aws --version
      - run:
          name: directory
          command: |
            ls -a
      - run:
          name: docker prune
          command: |
            docker image prune --all
      - run:
          name: docker build
          command: |
            docker-compose -f docker-compose-build.yaml build --parallel
      - run:
          name: docker up
          command: |
            docker-compose up
      # - deploy:
      #     name: Push application Docker image
      #     command: |
      # docker login -u $DOCKER_HUB_USER_ID -p $DOCKER_HUB_PWD
